version: '3'
services:
  spring-app:
    image: demo-application:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

volumes:
  dynamodb_data:
