package com.example.entity;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Score")
public class Score {

    private String id;

    private double value;

    private String studentId;

    private String classId;

    @DynamoDBAttribute
    public String getStudentId() {
        return studentId;
    }
    @DynamoDBAttribute
    public String getClassId() {
        return classId;
    }

    @DynamoDBAttribute
    public double getValue() {
        return value;
    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public void setId(String id) {
        this.id = id;
    }
}
