package com.example.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Student")
public class Student {
    private String id;
    private String classNumber;
    private String name;
    private Set<String> classIds = new HashSet<>();
    private List<Class> classes = new ArrayList<>();
    private List<StudentScore> scores = new ArrayList<>();
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return id;
    }

    @DynamoDBAttribute
    public String getName(){
        return name;
    }
    @DynamoDBAttribute
    public String getClassNumber(){
        return classNumber;
    }

    public void setId(String id){
        this.id = id;
    }

    public void setName(String name){
        this.name = name;
    }

    public void setClassNumber(String classNumber){
        this.classNumber = classNumber;
    }

    @DynamoDBAttribute
    public Set<String> getClassIds() {
        return classIds;
    }

    public void setClassIds(Set<String> classIds) {
        this.classIds = classIds;
    }

    public List<Class> getClasses() {
        return classes;
    }

    public void setClasses(List<Class> classes) {
        this.classes = classes;
    }

    public void setScores(List<StudentScore> scores){ this.scores = scores; }

}
